name: try

on:
  [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event ${{ github.event_name }}"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
      - name: Try it
        run: |
          cd basic
          yarn install
          yarn try
