name: try

on:
  [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event ${{ github.event_name }}"
      - uses: actions/checkout
      - name: Try it
        run: yarn try
